const uaInstruments = [
  ['guitar', 'pink', 'Гітара', 'з нуля — advanced', '6 курсів', 'photo-1510915361894-db8b60106cb1', 'Гітарист грає на електрогітарі'],
  ['drums', 'lime', 'Ударні', 'ритм починається тут', '4 курси', 'photo-1516280440614-37939bbacd81', 'Музикант виступає на сцені'],
  ['keys', 'violet', 'Клавіші', 'від перших нот', '5 курсів', 'photo-1520523839897-bd0b52f945a0', 'Клавішні на репетиції'],
  ['vocals', 'orange', 'Вокал', 'знайди свій голос', '3 курси', 'photo-1516280440614-37939bbacd81', 'Співачка на сцені'],
  ['bass', 'blue', 'Бас', 'відчуй фундамент', '4 курси', 'photo-1493225457124-a3eb161ffa5f', 'Басист на концерті'],
  ['production', 'pink', 'Продакшн', 'музика з голови — в навушники', '3 курси', 'photo-1598488035139-bdbb2231ce04', 'Домашня студія звукозапису'],
].map(([id, color, name, level, short, image, alt]) => ({ id, icon: id, color, name, level, short, image, alt }))
const enInstruments = [
  ['guitar', 'pink', 'Guitar', 'zero to advanced', '6 courses', 'photo-1510915361894-db8b60106cb1', 'Guitarist playing an electric guitar'],
  ['drums', 'lime', 'Drums', 'find your rhythm', '4 courses', 'photo-1516280440614-37939bbacd81', 'Musician performing on stage'],
  ['keys', 'violet', 'Keys', 'from your first note', '5 courses', 'photo-1520523839897-bd0b52f945a0', 'Keys in a rehearsal space'],
  ['vocals', 'orange', 'Vocals', 'find your voice', '3 courses', 'photo-1516280440614-37939bbacd81', 'Singer performing on stage'],
  ['bass', 'blue', 'Bass', 'feel the foundation', '4 courses', 'photo-1493225457124-a3eb161ffa5f', 'Bassist playing live'],
  ['production', 'pink', 'Production', 'headphones on, world off', '3 courses', 'photo-1598488035139-bdbb2231ce04', 'A home recording studio'],
].map(([id, color, name, level, short, image, alt]) => ({ id, icon: id, color, name, level, short, image, alt }))

const uaItems = [
  ['guitar','pink','photo-1510915361894-db8b60106cb1','Гра на електрогітарі','ВІДЕО + LIVE','ГІТАРА','6 тижнів','Шість струн, нуль страху','Акорди, ритм і перші пісні, які можна зіграти повністю.',['beginner'],'₴1 490'],
  ['drums','lime','photo-1516280440614-37939bbacd81','Музикант на сцені','ВІДЕО','УДАРНІ','8 тижнів','Ритм у твоїх руках','Координація, грув і впевненість за установкою з нуля.',['beginner','intermediate'],'₴1 790'],
  ['keys','violet','photo-1520523839897-bd0b52f945a0','Клавішні інструменти','LIVE','КЛАВІШІ','5 тижнів','Улюблені пісні на клавішах','Навчись чути гармонії та грати улюблене без нотного стресу.',['beginner','intermediate'],'₴1 390'],
  ['vocals','orange','photo-1516280440614-37939bbacd81','Вокаліст на концерті','LIVE + ВІДЕО','ВОКАЛ','4 тижні','Голос без фільтрів','Дихання, опора й сміливість звучати по-своєму.',['beginner','intermediate','advanced'],'₴1 590'],
  ['bass','blue','photo-1493225457124-a3eb161ffa5f','Басист під світлом сцени','ВІДЕО','БАС','6 тижнів','Низько — це глибоко','Грув, звук і фундамент, який тримає всю пісню.',['beginner','advanced'],'₴1 490'],
  ['production','pink','photo-1598488035139-bdbb2231ce04','Студія для запису музики','ВІДЕО','ПРОДАКШН','7 тижнів','Записуй, як відчуваєш','Збери свій перший трек від ідеї до останнього експорту.',['intermediate','advanced'],'₴1 890'],
]
const enItems = [
  ['guitar','pink','photo-1510915361894-db8b60106cb1','Playing an electric guitar','VIDEO + LIVE','GUITAR','6 weeks','Six Strings, Zero Fear','Chords, rhythm, and the first songs you can play all the way through.',['beginner'],'$39'],
  ['drums','lime','photo-1516280440614-37939bbacd81','Musician on stage','VIDEO','DRUMS','8 weeks','Rhythm in Your Hands','Build coordination, groove, and confidence behind the kit from scratch.',['beginner','intermediate'],'$46'],
  ['keys','violet','photo-1520523839897-bd0b52f945a0','Keyboard instruments','LIVE','KEYS','5 weeks','Songs You Love on Keys','Hear harmony and play what you love without the sheet-music stress.',['beginner','intermediate'],'$36'],
  ['vocals','orange','photo-1516280440614-37939bbacd81','Vocalist at a live concert','LIVE + VIDEO','VOCALS','4 weeks','A Voice Without Filters','Breath, support, and the confidence to sound like yourself.',['beginner','intermediate','advanced'],'$41'],
  ['bass','blue','photo-1493225457124-a3eb161ffa5f','Bassist under stage lights','VIDEO','BASS','6 weeks','Low End, Deep Feel','Groove, tone, and the foundation holding the whole song together.',['beginner','advanced'],'$39'],
  ['production','pink','photo-1598488035139-bdbb2231ce04','A music recording studio','VIDEO','PRODUCTION','7 weeks','Record It Your Way','Build your first track from an idea to the final export.',['intermediate','advanced'],'$49'],
]
const items = (rows) => rows.map(([icon,color,image,alt,format,instrument,duration,title,description,levels,price]) => ({ icon,color,image,alt,format,instrument,duration,title,description,levels,price }))

export const copy = {
  ua: {
    nav:{courses:'Курси',instructors:'Викладачі',pricing:'Ціни',contact:'Контакти'}, header:{strip:'НЕ ТРЕБА ДОЗВОЛУ, ЩОБ ЗАГУЧАТИ',strip2:'УРОКИ МУЗИКИ ДЛЯ ВСІХ',menu:'Головна навігація',start:'Почати навчання',language:'Перемкнути мову',open:'Відкрити меню',close:'Закрити меню'}, ticker:'ВІД ПЕРШОГО АКОРДУ ДО ВЛАСНОГО ЗВУКУ', levels:{beginner:'Початківець',intermediate:'Середній',advanced:'Просунутий'}, instruments:uaInstruments,
    home:{kicker:'ТВОЯ МУЗИЧНА ЕРА ПОЧИНАЄТЬСЯ ТУТ',h1:'ГРАЙ',hint:'на чому завгодно',h2:'СВОЄ.',h3:'ЗАВЖДИ.',intro:'Гітара чи ударні. Перший акорд чи складне соло. Навчайся у своєму темпі, зі своїми людьми — і грай так, як звучиш саме ти.',cta:'Обрати інструмент',secondary:'Подивитися формати',scribble:'без правил!',sticker:'ТВОЯ ЧЕРГА',vertical:'НЕ ВІДКЛАДАЙ СВІЙ ЗВУК',foot:'МУЗИЧНА ШКОЛА БЕЗ ДРЕС-КОДУ',photoAlt:'Гітарист грає на електрогітарі',stageAlt:'Натовп на концерті',categories:'ЗНАЙДИ СВІЙ ШУМ',categoryTitle:'Один сайт.\nУсі інструменти.',categoryText:'Без «я вже запізно почав». Без «це не для мене». Є цікавість? Цього досить.',categoryFoot:'ВІД ПЕРШОГО РАЗУ ДО ЩЕ ОДНОГО НА БІС',allCourses:'Усі курси',formatLabel:'ДВА ШЛЯХИ. ОДИН ЗВУК.',formatTitle:'Обирай темп.',recordedLabel:'У ЗАПИСІ',recordedTitle:'Твій плей.\nТвій темп.',recordedText:'Короткі відеоуроки, які вмикаються саме тоді, коли тобі зручно. Пауза, повтор, ще раз — скільки треба.',recordedLink:'Дивитися курси',recordedAlt:'Музиканти виступають під світлом сцени',liveLabel:'НАЖИВО',liveTitle:'Живий звук.\nЖивий фідбек.',liveText:'Зустрічі з викладачами, які справді грають. Питай, пробуй, збивайся з ритму — для того й зустрілись.',liveLink:'Наші викладачі',liveAlt:'Клавішні в репетиційній студії',stamp:'ПИТАННЯ\nОКЕЙ!',manifestoLabel:'ЖОДНИХ ПРОСЛУХОВУВАНЬ',manifesto1:'ТУТ НЕ ТРЕБА ',manifestoAccent:'ВРАЖАТИ.',manifesto2:' ТРЕБА ГРАТИ.',manifestoText:'Неважливо, скільки тобі років, на якому рівні ти зараз і скільки разів кидав інструмент. Тут можна просто почати знову.',manifestoCta:'Знайти своє',voicesLabel:'СЛОВА ПІСЛЯ ПЕРШОЇ НОТИ',voicesTitle:'Їм уже грається.',voicesNote:'не оцінка — відгук',voicesFoot:'Твоя історія теж може бути наступною.'},
    reviews:[{name:'Аня, 34',detail:'бас · грає 4 місяці',text:'Я думала, що бас — це для якихось особливих людей. Виявилося, що він для людей, які люблять відчувати музику всім тілом.',image:'photo-1534528741775-53994a69daeb'},{name:'Сашко, 17',detail:'ударні · початківець',text:'Можна передивитися урок хоч двадцять разів. І ніхто не закочує очі, коли я знову збиваюся на тому самому місці.',image:'photo-1500648767791-00dcc994a43e'},{name:'Олена, 52',detail:'клавіші · для себе',text:'Пішла «просто спробувати». Тепер граю ту пісню, яку завжди хотіла. Не ідеально, зате моя.',image:'photo-1544005313-94ddf0286df2'}],
    courses:{eyebrow:'КАТАЛОГ ЗВУКІВ',title:'ОБЕРИ СВІЙ',accent:'ІНСТРУМЕНТ.',intro:'Відеоуроки та живі заняття. Починай з нуля, повертайся після паузи або стрибай на наступний рівень.',deco:'06 ІНСТРУМЕНТІВ · 1 ТВОЯ ІСТОРІЯ',instrument:'ІНСТРУМЕНТ',level:'РІВЕНЬ',all:'Усі',anyLevel:'Будь-який рівень',empty:'На цю комбінацію фільтрів курсів поки немає. Спробуй інший інструмент.',once:'разово',ask:'Запитати про курс',bottom:'НЕ ЗНАЄШ, З ЧОГО ПОЧАТИ?',help:'Допоможемо обрати',items:items(uaItems)},
    instructors:{eyebrow:'НАША ГУЧНА КОМПАНІЯ',title:'ЛЮДИ, ЯКІ',accent:'ГРАЮТЬ.',intro:'Викладачі, які пам’ятають першу репетицію. І добре знають, що з нею робити.',deco:'СВОЇ ЛЮДИ · СВІЙ ЗВУК',book:'Записатися до викладача',note:'Тут не читають лекції згори. Тут сідають поруч і грають разом.',cta:'Знайомитись ближче',people:[{name:'Марта Коваль',instrument:'ВОКАЛ',years:'9 РОКІВ',image:'photo-1534528741775-53994a69daeb',bio:'Співає соул, не боїться тиші між нотами й навчає знаходити опору без надриву.',sticker:'ДИХАЙ!',tag:'SOUL / JAZZ / ТВОЄ'},{name:'Денис Левченко',instrument:'БАС',years:'12 РОКІВ',image:'photo-1500648767791-00dcc994a43e',bio:'Колись грав у гаражних панк-бендах. Тепер допомагає почути всю музику знизу.',sticker:'LOW END',tag:'FUNK / GROOVE / ROCK'},{name:'Іра Гайдук',instrument:'БАРАБАНИ',years:'7 РОКІВ',image:'photo-1544005313-94ddf0286df2',bio:'Її правило: помилка — це просто цікавий ритмічний поворот. Спробуй ще раз.',sticker:'НА РАЗ!',tag:'INDIE / ROCK / RHYTHM'},{name:'Сашко Таран',instrument:'ГІТАРА',years:'15 РОКІВ',image:'photo-1506794778202-cad84cf45f1d',bio:'Педальборд знає напам’ять, але починає кожен урок із запитання: «Що ти хочеш грати?»',sticker:'ПЕРШИЙ РІФФ',tag:'ROCK / BLUES / RIFFS'}]},
    pricing:{eyebrow:'ВІЛЬНИЙ ВХІД. ЧЕСНИЙ ПРАЙС.',title:'ПЛАТИ ЯК',accent:'ЗРУЧНО.',intro:'Один курс, до якого давно придивляєшся. Або весь музичний всесвіт — за одну місячну підписку.',deco:'₴ ₴ ₴',currency:'₴',singleTag:'ОДИН КУРС',singleSticker:'БЕЗ ПІДПИСКИ',singleTitle:'Мій трек.\nМої правила.',singleText:'Обирай курс, зберігай доступ і повертайся, коли буде натхнення.',singlePrice:'1 490',once:'/ разово',singleFeatures:['Повна програма одного курсу','Відеоуроки — назавжди','Завдання й матеріали','Без автоматичних списань'],singleCta:'Обрати курс',subTag:'УСЯ ПЛАТФОРМА',popular:'УЛЮБЛЕНИЙ ФОРМАТ',subTitle:'Усі інструменти.\nОдин ритм.',subText:'Ходи між інструментами, форматами й рівнями. Навчайся, скільки хочеш.',subPrice:'790',month:'/ місяць',subFeatures:['Усі відеокурси платформи','Нова музика щомісяця','Знижка на живі заняття','Скасовуй будь-коли'],subCta:'Почати з підпискою',cancel:'Жодних зобов’язань. Справді.',note:'Не впевнена, який формат підійде? Розкажи нам, чого хочеш навчитися, — підкажемо.',ask:'Запитати поради'},
    contact:{eyebrow:'ПИШИ. ДЗВОНИ. ГРАЙ.',title:'ДАВАЙ',accent:'ЗНАЙОМИТИСЬ.',intro:'Не знаєш, з якого інструмента почати? Хочеш поговорити з викладачем? Просто напиши нам.',deco:'НЕ КУСАЄМОСЬ :)',direct:'НАПРЯМУ',directText:'Пишемо у відповідь живі люди. Зазвичай протягом одного робочого дня.',response:'У МУЗИЦІ — 7 ДНІВ НА ТИЖДЕНЬ',formTitle:'АБО ЗАЛИШ ПОВІДОМЛЕННЯ',name:'Як до тебе звертатися?',nameHint:'Твоє ім’я',email:'Електронна пошта',topic:'ТЕМА',topicHint:'Обери тему',topics:['Підібрати курс','Питання про підписку','Живе заняття','Інше'],message:'Що хочеш дізнатися?',messageHint:'Тут можна питати будь-що…',send:'Відправити',sent:'Відправлено',success:'Дякуємо! Ми вже налаштовуємо відповідь.',faqLabel:'ПИТАННЯ, ЯКІ ЗВУЧАТЬ ЧАСТО',faqTitle:'А якщо…',faqSticker:'ЗАПИТУЙ!',faqs:[{q:'У чому різниця між відеокурсом і заняттям наживо?',a:'Відеокурс дивишся коли зручно, повертаєшся до уроків і вчишся у власному ритмі. На живих заняттях зустрічаєшся з викладачем, ставиш запитання та одразу отримуєш фідбек. Можна обрати одне або поєднати обидва формати.'},{q:'Чи можна скасувати підписку?',a:'Так, у будь-який момент — без штрафів і довгих розмов. Доступ до курсів зберігається до кінця вже оплаченого періоду.'},{q:'Мені потрібен власний інструмент?',a:'Для відеоуроків він знадобиться, але починати можна навіть з орендованого інструмента. Для живих занять залежить від формату: викладач підкаже, як краще підготуватися.'},{q:'А якщо я ніколи не грав/грала?',a:'Саме для тебе є курси з самого початку. Не треба вміти читати ноти, мати музичну освіту чи «особливий слух». Цікавість — уже достатній старт.'}]},
    footer:{scribble:'БЕЗ ДОЗВОЛУ. БЕЗ ПАУЗИ.',ctaLabel:'ТВІЙ НАСТУПНИЙ КРОК',ctaTitle:'ХОЧЕШ',ctaAccent:'ЗВУЧАТИ?',blurb:'Уроки музики для звичайних людей із незвичайно гучними мріями.',explore:'ПОКРУЖЛЯТИ',newsTitle:'ЛИСТИ З РЕПЕТИЦІЙНОЇ',newsText:'Нові курси, свіжі звуки й трохи натхнення. Без спаму, чесно.',newsHint:'Твій email',subscribe:'Підписатися на листи',thanks:'Є! Перевір пошту зовсім скоро.',bottom:'ЗРОБЛЕНО З ГУЧНІСТЮ У ЛЬВОВІ'}
  },
  en: {
    nav:{courses:'Courses',instructors:'Instructors',pricing:'Pricing',contact:'Contact'},header:{strip:'NO PERMISSION NEEDED TO MAKE SOME NOISE',strip2:'MUSIC LESSONS FOR EVERYONE',menu:'Main navigation',start:'Start learning',language:'Switch language',open:'Open menu',close:'Close menu'},ticker:'FROM YOUR FIRST CHORD TO YOUR OWN SOUND',levels:{beginner:'Beginner',intermediate:'Intermediate',advanced:'Advanced'},instruments:enInstruments,
    home:{kicker:'YOUR MUSICAL ERA STARTS HERE',h1:'PLAY',hint:'whatever you want',h2:'YOUR.',h3:'ALWAYS.',intro:'Guitar or drums. First chord or a gnarly solo. Learn at your pace, with your people, and play in a way that sounds like you.',cta:'Pick an instrument',secondary:'See how it works',scribble:'no rules!',sticker:'YOUR TURN',vertical:'YOUR SOUND WON’T WAIT',foot:'A MUSIC SCHOOL WITH NO DRESS CODE',photoAlt:'Guitarist playing an electric guitar',stageAlt:'Crowd at a concert',categories:'FIND YOUR NOISE',categoryTitle:'One place.\nEvery instrument.',categoryText:'No “I started too late.” No “that’s not for me.” Curious? That’s plenty.',categoryFoot:'FROM FIRST TRY TO ONE MORE ENCORE',allCourses:'All courses',formatLabel:'TWO WAYS. ONE SOUND.',formatTitle:'Pick your pace.',recordedLabel:'ON DEMAND',recordedTitle:'Your playlist.\nYour pace.',recordedText:'Short video lessons ready when you are. Pause, rewind, play it again as many times as you need.',recordedLink:'Browse courses',recordedAlt:'Stage lights and musicians performing live',liveLabel:'IN REAL TIME',liveTitle:'Real people.\nReal feedback.',liveText:'Meet teachers who really play. Ask, try, lose the beat. That’s what they’re there for.',liveLink:'Meet the teachers',liveAlt:'Keyboard in a rehearsal studio',stamp:'QUESTIONS\nWELCOME!',manifestoLabel:'NO AUDITIONS. EVER.',manifesto1:'YOU DON’T HAVE TO ',manifestoAccent:'IMPRESS.',manifesto2:' JUST PLAY.',manifestoText:'Doesn’t matter how old you are, where you’re starting, or how many times you’ve put your instrument down. You can just start again here.',manifestoCta:'Find your sound',voicesLabel:'WORDS AFTER THE FIRST NOTE',voicesTitle:'They’re already playing.',voicesNote:'not a score — a story',voicesFoot:'Your story could be next.'},
    reviews:[{name:'Anya, 34',detail:'bass · 4 months in',text:'I thought bass was for some special kind of person. Turns out it’s for people who like feeling the music with their whole body.',image:'photo-1534528741775-53994a69daeb'},{name:'Sasha, 17',detail:'drums · beginner',text:'I can replay a lesson twenty times. Nobody rolls their eyes when I miss the same bit again.',image:'photo-1500648767791-00dcc994a43e'},{name:'Olena, 52',detail:'keys · just for me',text:'I came “just to try.” Now I can play that song I’ve always wanted to. Not perfectly, but it’s mine.',image:'photo-1544005313-94ddf0286df2'}],
    courses:{eyebrow:'THE SOUND CATALOG',title:'PICK YOUR',accent:'INSTRUMENT.',intro:'Video lessons and live sessions. Start from scratch, shake off the dust, or jump to your next level.',deco:'06 INSTRUMENTS · 1 YOUR STORY',instrument:'INSTRUMENT',level:'LEVEL',all:'All',anyLevel:'Any level',empty:'No courses match those filters yet. Try another instrument.',once:'one-time',ask:'Ask about',bottom:'NOT SURE WHERE TO START?',help:'We’ll help you pick',items:items(enItems)},
    instructors:{eyebrow:'OUR LOUD LITTLE CREW',title:'PEOPLE WHO',accent:'PLAY.',intro:'Teachers who remember their first rehearsal. And know exactly what to do with one.',deco:'GOOD PEOPLE · GOOD NOISE',book:'Book a lesson with',note:'No lectures from a distance. We sit down and play together.',cta:'Come say hello',people:[{name:'Marta Koval',instrument:'VOCALS',years:'9 YEARS',image:'photo-1534528741775-53994a69daeb',bio:'Soul singer, unafraid of the quiet between notes. Teaches support without strain.',sticker:'BREATHE!',tag:'SOUL / JAZZ / YOU'},{name:'Denys Levchenko',instrument:'BASS',years:'12 YEARS',image:'photo-1500648767791-00dcc994a43e',bio:'Used to play in garage punk bands. Now helps you hear the whole song from below.',sticker:'LOW END',tag:'FUNK / GROOVE / ROCK'},{name:'Ira Haiduk',instrument:'DRUMS',years:'7 YEARS',image:'photo-1544005313-94ddf0286df2',bio:'Their rule: a mistake is just an interesting rhythmic detour. Try again.',sticker:'ON THE 1!',tag:'INDIE / ROCK / RHYTHM'},{name:'Sasha Taran',instrument:'GUITAR',years:'15 YEARS',image:'photo-1506794778202-cad84cf45f1d',bio:'Knows every pedalboard by heart, but starts every lesson with: “What do you want to play?”',sticker:'FIRST RIFF',tag:'ROCK / BLUES / RIFFS'}]},
    pricing:{eyebrow:'OPEN DOOR. HONEST PRICES.',title:'PAY YOUR',accent:'WAY.',intro:'One course you’ve had your eye on. Or the whole musical universe for one monthly pass.',deco:'$ $ $',currency:'$',singleTag:'ONE COURSE',singleSticker:'NO SUBSCRIPTION',singleTitle:'My track.\nMy rules.',singleText:'Pick a course, keep access, come back whenever inspiration strikes.',singlePrice:'39',once:'/ one time',singleFeatures:['Full access to one course','Video lessons — yours for good','Exercises and materials','No automatic charges'],singleCta:'Choose a course',subTag:'THE WHOLE PLATFORM',popular:'A FAN FAVORITE',subTitle:'Every instrument.\nOne rhythm.',subText:'Move between instruments, formats, and levels. Learn as much as you like.',subPrice:'19',month:'/ month',subFeatures:['Every video course on the platform','New music every month','Discounts on live lessons','Cancel whenever you want'],subCta:'Get full access',cancel:'No strings attached. Seriously.',note:'Not sure which format fits? Tell us what you’d love to learn and we’ll point you in the right direction.',ask:'Ask us anything'},
    contact:{eyebrow:'WRITE. CALL. PLAY.',title:'LET’S',accent:'MEET.',intro:'Not sure which instrument to pick? Want to talk to a teacher? Just say hello.',deco:'WE DON’T BITE :)',direct:'STRAIGHT UP',directText:'Real people read your messages. Usually within one business day.',response:'MUSIC’S ON — 7 DAYS A WEEK',formTitle:'OR DROP US A NOTE',name:'What should we call you?',nameHint:'Your name',email:'Email address',topic:'TOPIC',topicHint:'Pick a topic',topics:['Help picking a course','Subscription question','Live lesson','Something else'],message:'What’s on your mind?',messageHint:'Ask us absolutely anything…',send:'Send it',sent:'Sent',success:'Thanks! We’re already tuning up a reply.',faqLabel:'QUESTIONS WE HEAR A LOT',faqTitle:'What if…',faqSticker:'ASK US!',faqs:[{q:'What’s the difference between a video course and a live lesson?',a:'Watch a video course whenever you like, revisit each lesson, and learn at your own pace. Live sessions mean meeting a teacher, asking questions, and getting instant feedback. Pick one, or mix both.'},{q:'Can I cancel my subscription?',a:'Any time — no fees, no lengthy chats. Course access lasts until the end of your paid period.'},{q:'Do I need my own instrument?',a:'You’ll need one for video lessons, though you can start with a rental. It depends on the format for live lessons; your teacher will help you figure out what to bring.'},{q:'What if I’ve never played before?',a:'That’s exactly what our beginner courses are for. You don’t need to read sheet music, have formal training, or possess a “special ear.” Curiosity is more than enough.'}]},
    footer:{scribble:'NO PERMISSION. NO PAUSE.',ctaLabel:'YOUR NEXT MOVE',ctaTitle:'READY TO',ctaAccent:'MAKE NOISE?',blurb:'Music lessons for everyday people with unreasonably big musical dreams.',explore:'TAKE A LOOK',newsTitle:'POSTCARDS FROM THE PRACTICE ROOM',newsText:'New courses, fresh sounds, and a little inspiration. No spam, promise.',newsHint:'Your email',subscribe:'Subscribe to the newsletter',thanks:'You’re in! Keep an eye on your inbox.',bottom:'MADE LOUD IN LVIV'}
  }
}